sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 0.12
  - 4
  - 6
  - 8

before_install:
  - mkdir node_modules; ln -s ../ node_modules/duration

notifications:
  email:
    - medikoo+duration@medikoo.com

script: "npm test && npm run lint"
